name: Epic / Large Feature
description: Track a large feature or initiative with multiple sub-issues
title: "[EPIC]: "
labels: ["epic", "planning"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this template for large features or initiatives that will be broken down into multiple issues.

  - type: textarea
    id: epic-description
    attributes:
      label: Epic Description
      description: A comprehensive description of this epic/initiative
      placeholder: Describe the overall goal and scope...
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: What business value does this epic deliver?
      placeholder: |
        - Increase conversion rate
        - Improve customer satisfaction
        - Reduce support tickets
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Key user stories this epic addresses
      placeholder: |
        - As a customer, I want to...
        - As an admin, I want to...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this epic?
      options:
        - P0 (Critical)
        - P1 (High)
        - P2 (Medium)
        - P3 (Low)
    validations:
      required: true

  - type: input
    id: target-release
    attributes:
      label: Target Release
      description: Target release or milestone
      placeholder: v2.0.0 or Q2 2026

  - type: textarea
    id: success-metrics
    attributes:
      label: Success Metrics
      description: How will we measure success?
      placeholder: |
        - Metric 1: ...
        - Metric 2: ...

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What dependencies does this epic have?
      placeholder: |
        - External API integration
        - Third-party service
        - Other epics

  - type: textarea
    id: risks
    attributes:
      label: Risks and Mitigation
      description: What risks should we be aware of?
      placeholder: |
        - Risk: ...
          Mitigation: ...

  - type: textarea
    id: sub-issues
    attributes:
      label: Sub-Issues
      description: Break this epic down into specific issues (will be created as separate issues)
      placeholder: |
        - [ ] #123 - Database schema design
        - [ ] #124 - API endpoint implementation
        - [ ] #125 - Frontend UI components
        - [ ] #126 - Integration testing
        - [ ] #127 - Documentation
        - [ ] #128 - Performance optimization
    validations:
      required: true

  - type: textarea
    id: phases
    attributes:
      label: Implementation Phases
      description: Break down the work into phases
      placeholder: |
        ## Phase 1: Planning & Design
        - [ ] Requirements gathering
        - [ ] Technical design
        - [ ] UI/UX mockups
        
        ## Phase 2: Development
        - [ ] Backend implementation
        - [ ] Frontend implementation
        - [ ] Integration
        
        ## Phase 3: Testing & Launch
        - [ ] QA testing
        - [ ] Bug fixes
        - [ ] Deployment
        - [ ] Monitoring
