name: Feature Request
description: Suggest a new feature for the Asper Beauty Shop
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a user, I want to... so that...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe any alternative solutions...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking)
        - High (Very important)
        - Medium (Would be nice)
        - Low (Nice to have)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application does this affect?
      multiple: true
      options:
        - Product Catalog
        - Shopping Cart
        - Checkout
        - User Account
        - Search
        - Navigation
        - Mobile Experience
        - Performance
        - Accessibility
        - Internationalization
        - Admin/Backend
        - Other
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add mockups, wireframes, or examples from other sites
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know when this feature is complete?
      placeholder: |
        - [ ] Users can...
        - [ ] The system should...
        - [ ] Performance meets...

  - type: textarea
    id: implementation-subtasks
    attributes:
      label: Implementation Sub-Tasks
      description: Break down the implementation into smaller tasks
      placeholder: |
        - [ ] Design database schema
        - [ ] Create API endpoints
        - [ ] Build UI components
        - [ ] Add validation
        - [ ] Write tests
        - [ ] Update documentation
        - [ ] Add analytics tracking
